Repository dbt-labs/dbt-snowflake, pull requests merged in 2021-11, with the labels that each got.

#39 Use long description for PyPi
  setup.py
Labels: cla:yes

#36 add host/port/protocol as optional profile parameters
  CHANGELOG.md
  dbt/adapters/snowflake/connections.py
Labels: cla:yes, ok to test

#43 Bump artifact versions in tests
  .github/workflows/integration.yml
  .github/workflows/main.yml
  tests/integration/docs_generate_tests/test_docs_generate.py
  tests/integration/sources_test/test_sources.py
Labels: cla:yes

#38 Use common columns for incremental schema changes
  CHANGELOG.md
  dbt/include/snowflake/macros/materializations/incremental.sql
  tests/integration/incremental_schema_tests/models/incremental_append_new_columns_remove_one.sql
  tests/integration/incremental_schema_tests/models/incremental_append_new_columns_remove_one_target.sql
  tests/integration/incremental_schema_tests/models/schema.yml
  tests/integration/incremental_schema_tests/test_incremental_schema.py
  tests/integration/incremental_schema_tests/tests/select_from_incremental_append_new_columns_remove_one.sql
  tests/integration/incremental_schema_tests/tests/select_from_incremental_append_new_columns_remove_one_target.sql
Labels: cla:yes, ok to test

#44 Bump snowflake-connector-python to `>=2.4.1,<2.8.0`
  CHANGELOG.md
  setup.py
Labels: cla:yes, test snowflake

#46 Fix tests failing due to dbt-core changes
  .github/workflows/main.yml
  CHANGELOG.md
  setup.py
  tests/integration/docs_generate_tests/test_docs_generate.py
  tests/unit/utils.py
  tox.ini
Labels: cla:yes

#42 add support for new struct logging
  CHANGELOG.md
  dbt/adapters/snowflake/connections.py
  tests/integration/base.py
  tests/integration/query_comments_test/test_query_comments.py
  tests/unit/test_snowflake_adapter.py
Labels: cla:yes

#6 adding snowflake connector open connection retries
  CHANGELOG.md
  dbt/adapters/snowflake/connections.py
Labels: cla:yes, ok to test

#50 Slack alerts for failed nightly tests
  .github/workflows/integration.yml
Labels: cla:yes

#48 Fix: Support individual query tag configuration for Seeds and Snapshots
  CHANGELOG.md
  dbt/include/snowflake/macros/materializations/seed.sql
  dbt/include/snowflake/macros/materializations/snapshot.sql
  tests/integration/simple_seed_test/check-query-tag-expected/check_query_tag.sql
  tests/integration/simple_seed_test/test_seed_with_query_tag.py
  tests/integration/simple_snapshot_test/check-snapshots-query-tag-expected/check_query_tag.sql
  tests/integration/simple_snapshot_test/check-snapshots-query-tag/snapshot.sql
  tests/integration/simple_snapshot_test/test_snapshot_query_tag.py
Labels: cla:yes, ok to test

#49 Update connections.py
  CHANGELOG.md
  dbt/adapters/snowflake/connections.py
  tests/unit/test_snowflake_adapter.py
Labels: cla:yes, ok to test

#53 Add column comments to Snowflake views
  CHANGELOG.md
  dbt/include/snowflake/macros/adapters.sql
  tests/integration/column_comments_tests/models/quote_model.sql
  tests/integration/column_comments_tests/models/schema.yml
  tests/integration/column_comments_tests/test_column_comments.py
Labels: cla:yes, ok to test

#57 Refactor query tag tests
  tests/integration/query_tag_tests/macros/check_tag.sql
  tests/integration/query_tag_tests/models/incremental_model_query_tag.sql
  tests/integration/query_tag_tests/models/table_model_query_tag.sql
  tests/integration/query_tag_tests/models/view_model_query_tag.sql
  tests/integration/query_tag_tests/seeds/seed_query_tag.csv
  tests/integration/query_tag_tests/snapshots/snapshot_query_tag.sql
  tests/integration/query_tag_tests/test_query_tags.py
  tests/integration/simple_seed_test/check-query-tag-expected/check_query_tag.sql
  tests/integration/simple_seed_test/test_seed_with_query_tag.py
  tests/integration/simple_snapshot_test/test_snapshot_query_tag.py
Labels: cla:yes, test all
