Repository dbt-labs/dbt-snowflake, pull requests merged in 2022-06, with the labels that each got.

#167 Ct 605/docs generate test
  tests/functional/adapter/expected_stats.py
  tests/functional/adapter/test_basic.py
  tests/integration/docs_generate_tests/assets/lorem-ipsum.txt
  tests/integration/docs_generate_tests/cross_db_models/model.sql
  tests/integration/docs_generate_tests/cross_db_models/schema.yml
  tests/integration/docs_generate_tests/fail_macros/failure.sql
  tests/integration/docs_generate_tests/macros/dummy_test.sql
  tests/integration/docs_generate_tests/macros/macro.md
  tests/integration/docs_generate_tests/macros/schema.yml
  tests/integration/docs_generate_tests/models/model.sql
  tests/integration/docs_generate_tests/models/readme.md
  tests/integration/docs_generate_tests/models/schema.yml
  tests/integration/docs_generate_tests/models/second_model.sql
  tests/integration/docs_generate_tests/ref_models/docs.md
  tests/integration/docs_generate_tests/ref_models/ephemeral_copy.sql
  tests/integration/docs_generate_tests/ref_models/ephemeral_summary.sql
  tests/integration/docs_generate_tests/ref_models/schema.yml
  tests/integration/docs_generate_tests/ref_models/view_summary.sql
  tests/integration/docs_generate_tests/seed/schema.yml
  tests/integration/docs_generate_tests/seed/seed.csv
  tests/integration/docs_generate_tests/snapshot/snapshot_seed.sql
  tests/integration/docs_generate_tests/test_docs_generate.py
  tests/integration/docs_generate_tests/trivial_models/model.sql
Labels: cla:yes, tech_debt

#171 Bump cryptography restraint upper bound to <37.0.0
  CHANGELOG.md
  setup.py
Labels: cla:yes, ok to test, test snowflake

#132 add set/unset_query_tag to the dbt macro namespace
  CHANGELOG.md
  dbt/include/snowflake/macros/adapters.sql
Labels: cla:yes, ok to test

#173 [BACKPORT] #166
  .github/workflows/integration.yml
  .github/workflows/main.yml
  .github/workflows/version-bump.yml
  CONTRIBUTING.MD
Labels: cla:yes

#146 Adding Python 3.10 to test matrix
  .github/scripts/integration-test-matrix.js
  .github/workflows/main.yml
  .pre-commit-config.yaml
  CONTRIBUTING.MD
  dbt/__init__.py
  dev-requirements.txt
  mypy.ini
  setup.py
  tests/integration/base.py
  tox.ini
Labels: cla:yes, test all

#162 Lift + shift for cross-db macros
  dbt/include/snowflake/macros/utils/bool_or.sql
  dbt/include/snowflake/macros/utils/escape_single_quotes.sql
  dbt/include/snowflake/macros/utils/right.sql
  dbt/include/snowflake/macros/utils/safe_cast.sql
  tests/functional/adapter/test_utils.py
Labels: cla:yes

#153 Multi-query statements: fix rows_affected + query comments
  CHANGELOG.md
  dbt/adapters/snowflake/connections.py
  tests/functional/adapter/test_incremental_run_result.py
  tests/unit/test_snowflake_adapter.py
Labels: cla:yes, ready_for_review
