Repository dbt-labs/dbt-snowflake, pull requests merged in 2022-02, with the labels that each got.

#85 Adding Jira mirring Actions
  .github/workflows/jira-creation.yml
  .github/workflows/jira-label.yml
  .github/workflows/jira-transition.yml
Labels: cla:yes

#90 adding test.env.example to build local CI testing
  test.env.example
Labels: cla:yes

#96 Test incremental model with unique key both as string and list
  CHANGELOG.md
  tests/integration/docs_generate_tests/test_docs_generate.py
  tests/integration/incremental_unique_id_test/models/duplicated_unary_unique_key_list.sql
  tests/integration/incremental_unique_id_test/models/empty_str_unique_key.sql
  tests/integration/incremental_unique_id_test/models/empty_unique_key_list.sql
  tests/integration/incremental_unique_id_test/models/expected/one_str__overwrite.sql
  tests/integration/incremental_unique_id_test/models/expected/unique_key_list__inplace_overwrite.sql
  tests/integration/incremental_unique_id_test/models/no_unique_key.sql
  tests/integration/incremental_unique_id_test/models/nontyped_trinary_unique_key_list.sql
  tests/integration/incremental_unique_id_test/models/not_found_unique_key.sql
  tests/integration/incremental_unique_id_test/models/not_found_unique_key_list.sql
  tests/integration/incremental_unique_id_test/models/str_unique_key.sql
  tests/integration/incremental_unique_id_test/models/trinary_unique_key_list.sql
  tests/integration/incremental_unique_id_test/models/unary_unique_key_list.sql
  tests/integration/incremental_unique_id_test/seeds/add_new_rows.sql
  tests/integration/incremental_unique_id_test/seeds/duplicate_insert.sql
  tests/integration/incremental_unique_id_test/seeds/seed.csv
  tests/integration/incremental_unique_id_test/test_incremental_unique_id.py
Labels: enhancement, cla:yes

#65 enable mfa token cache for linux
  dbt/adapters/snowflake/connections.py
  tests/unit/test_snowflake_adapter.py
Labels: cla:yes, ok to test
