Repository dbt-labs/dbt-snowflake, pull requests merged in 2022-07, with the labels that each got.

#161 Improve column comment handling when `persist_docs` is enabled
  CHANGELOG.md
  dbt/include/snowflake/macros/adapters.sql
  tests/integration/persist_docs_tests/models-bigquery-nested/schema.yml
  tests/integration/persist_docs_tests/models-bigquery-nested/table_model_nested.sql
  tests/integration/persist_docs_tests/models-bigquery-nested/view_model_nested.sql
  tests/integration/persist_docs_tests/models/schema.yml
  tests/integration/persist_docs_tests/models/table_model.sql
  tests/integration/persist_docs_tests/models/view_model.sql
Labels: cla:yes, ok to test, ready_for_review

#189 Env vars for grantees for testing
  .github/workflows/integration.yml
Labels: cla:yes

#178 Ct 716 add materialization
  CHANGELOG.md
  dbt/adapters/snowflake/impl.py
  dbt/include/snowflake/macros/adapters.sql
  dbt/include/snowflake/macros/materializations/incremental.sql
  dbt/include/snowflake/macros/materializations/snapshot.sql
  dbt/include/snowflake/macros/materializations/table.sql
  dbt/include/snowflake/macros/materializations/view.sql
  dev-requirements.txt
  test.env.example
  tests/functional/adapter/test_grants.py
Labels: cla:yes

#186 Adding scheduled runs to release branches
  .github/workflows/integration.yml
  .github/workflows/release-branch-tests.yml
Labels: cla:yes

#197 add test for incremental model
  tests/functional/adapter/test_python_model.py
Labels: cla:yes

#185 Fixing broken 1.0.latest CI
  .github/workflows/integration.yml
  .github/workflows/main.yml
  .github/workflows/version-bump.yml
  dev_requirements.txt
Labels: cla:yes, test all

#196 Support dbt-core incremental refactor
  CHANGELOG.md
  dbt/adapters/snowflake/impl.py
  dbt/include/snowflake/macros/materializations/incremental.sql
Labels: cla:yes

#202 [Pytest conversion] test_warehouses
  tests/functional/warehouse_test/test_warehouses.py
  tests/integration/warehouse_test/models/expected_warehouse.sql
  tests/integration/warehouse_test/models/invalid_warehouse.sql
  tests/integration/warehouse_test/models/override_warehouse.sql
  tests/integration/warehouse_test/project-config-models/expected_warehouse.sql
  tests/integration/warehouse_test/project-config-models/override_warehouse.sql
  tests/integration/warehouse_test/test_warehouses.py
Labels: cla:yes

#182 Feature/python model v1
  CHANGELOG.md
  dbt/adapters/snowflake/impl.py
  dbt/include/snowflake/macros/adapters.sql
  dbt/include/snowflake/macros/materializations/incremental.sql
  dbt/include/snowflake/macros/materializations/table.sql
  dev-requirements.txt
  tests/functional/adapter/test_basic.py
  tests/functional/adapter/test_python_model.py
  tests/integration/defer_state_test/test_defer_state.py
Labels: cla:yes
