Repository dbt-labs/dbt-snowflake, pull requests merged in 2022-12, with the labels that each got.

#334 [CT-1458] [Feature] change default dbt-py method to anonymous stored procedures
  .changes/unreleased/Features-20221130-114307.yaml
  dbt/adapters/snowflake/impl.py
Labels: cla:yes

#333 reformatting alias test as part of spike fix in other areas
  tests/functional/adapter/test_aliases.py
Labels: cla:yes, Skip Changelog

#337 Python_models test reformat
  .changes/unreleased/Under the Hood-20221202-010112.yaml
  tests/functional/adapter/test_python_model.py
Labels: cla:yes

#345 Adjust tox passenv to be multiline
  tox.ini
Labels: cla:yes, Skip Changelog

#350 quote policy default_factory change
  .changes/unreleased/Fixes-20221209-125606.yaml
  dbt/adapters/snowflake/relation.py
Labels: cla:yes

#349 Correct the command for `make dev`
  .changes/unreleased/Fixes-20221209-114620.yaml
  Makefile
Labels: cla:yes

#356 Add release.yml
  .github/workflows/release.yml
Labels: cla:yes, Skip Changelog

#357 Fix changelog footer, update contributor list
  .changes/0.0.0.md
  .changie.yaml
Labels: cla:yes, Skip Changelog

#310 Incremental predicates testing
  .changes/unreleased/Features-20221128-134212.yaml
  dbt/include/snowflake/macros/materializations/incremental.sql
  dbt/include/snowflake/macros/materializations/merge.sql
  tests/functional/adapter/test_incremental_predicates.py
Labels: cla:yes, ready_for_review

#361 swap trigger, update commit sha on release workflow
  .github/workflows/release.yml
Labels: cla:yes, Skip Changelog

#362 add pypi release to workflow
  .github/workflows/release.yml
Labels: cla:yes, Skip Changelog

#367 Comment appropriate lines in `test.env.example`
  .changes/unreleased/Fixes-20221219-153345.yaml
  test.env.example
Labels: cla:yes

#360 Bump upper bound on `cryptography` to `<39.0.0`
  .changes/unreleased/Under the Hood-20221215-072655.yaml
  setup.py
Labels: cla:yes, ready_for_review

#369 Consistent capitalization for `CONTRIBUTING.md`
  .changes/unreleased/Under the Hood-20221219-163128.yaml
  .github/workflows/changelog-existence.yml
  CONTRIBUTING.md
Labels: cla:yes, ready_for_review
