Repository dbt-labs/dbt-snowflake, pull requests merged in 2022-11, with the labels that each got.

#309 convert warn_or_error to use specific event
  dbt/adapters/snowflake/connections.py
Labels: cla:yes, Skip Changelog

#307 [CT-1469] init pr for short term python version issue fix
  .github/workflows/integration.yml
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#280 Bump SCP upper bound to <2.9
  .changes/unreleased/Dependency-20220928-100113.yaml
  setup.py
Labels: cla:yes, dependencies

#319 [Backport][CT-1469] init pr for short term python version issue fix (#307)
  .github/workflows/integration.yml
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#317 [BACKPORT][CT-1469] #307 pr for short term python version issue fix
  .github/workflows/integration.yml
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#325 Snowflake Implementation of flake8 fix to swap gitlab for github
  .pre-commit-config.yaml
Labels: cla:yes, Skip Changelog, backport 1.1.latest, backport 1.2.latest, backport 1.3.latest

#322 convert oauth test to functional test
  tests/conftest.py
  tests/functional/oauth/test_oauth.py
  tests/integration/oauth_tests/models/model_1.sql
  tests/integration/oauth_tests/models/model_2.sql
  tests/integration/oauth_tests/models/model_3.sql
  tests/integration/oauth_tests/models/model_4.sql
  tests/integration/oauth_tests/test_oauth.py
Labels: cla:yes, Skip Changelog
