Repository dbt-labs/dbt-snowflake, pull requests merged in 2022-09, with the labels that each got.

#258 ignore adapter mypy check
  .changes/unreleased/Under the Hood-20220913-150316.yaml
  dbt/adapters/snowflake/__init__.py
Labels: cla:yes

#249 Update repo templates
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/regression-report.yml
  .github/ISSUE_TEMPLATE/release.md
  .github/pull_request_template.md
Labels: cla:yes, Skip Changelog

#244 Conversion of snowflake ephemeral test
  tests/functional/adapter/test_ephemeral.py
  tests/integration/ephemeral_test/models/base/base.sql
  tests/integration/ephemeral_test/models/base/base_copy.sql
  tests/integration/ephemeral_test/models/base/female_only.sql
  tests/integration/ephemeral_test/models/dependent.sql
  tests/integration/ephemeral_test/models/double_dependent.sql
  tests/integration/ephemeral_test/models/super_dependent.sql
  tests/integration/ephemeral_test/seed.sql
  tests/integration/ephemeral_test/test_ephemeral.py
Labels: cla:yes, Skip Changelog

#260 add a way to use anonymous sproc
  .changes/unreleased/Breaking Changes-20220913-171057.yaml
  .pre-commit-config.yaml
  dbt/adapters/snowflake/impl.py
  tests/functional/adapter/test_python_model.py
Labels: cla:yes

#252 [CT-1100] initial snowflake conversion of concurrency test
  tests/functional/adapter/test_concurrency.py
  tests/integration/concurrency_test/models/dep.sql
  tests/integration/concurrency_test/models/invalid.sql
  tests/integration/concurrency_test/models/skip.sql
  tests/integration/concurrency_test/models/table_a.sql
  tests/integration/concurrency_test/models/table_b.sql
  tests/integration/concurrency_test/models/view_model.sql
  tests/integration/concurrency_test/models/view_with_conflicting_cascade.sql
  tests/integration/concurrency_test/seed.sql
  tests/integration/concurrency_test/test_concurrency.py
  tests/integration/concurrency_test/update.sql
Labels: cla:yes, Skip Changelog

#263 support Imports in python model
  .changes/unreleased/Features-20220915-164525.yaml
  dbt/adapters/snowflake/impl.py
  tests/functional/adapter/test_python_model.py
Labels: cla:yes

#269 remove submit_python_job from context and additional PR feedback for #260
  .changes/unreleased/Under the Hood-20220913-171057.yaml
  dbt/adapters/snowflake/impl.py
Labels: cla:yes

#268 Jpmmcneill/snowflake type boolean
  .changes/unreleased/Features-20220920-000056.yaml
  tests/functional/adapter/utils/test_data_types.py
Labels: cla:yes, ready_for_review

#266 Fix [CT-1200]: Skip grants on share objects
  .changes/unreleased/Fixes-20220918-180550.yaml
  dbt/adapters/snowflake/impl.py
Labels: cla:yes, ready_for_review

#275 Tests for `current_timestamp`
  tests/functional/adapter/utils/test_utils.py
Labels: cla:yes, Skip Changelog

#257 Array macros
  .changes/unreleased/Features-20220913-084758.yaml
  dbt/include/snowflake/macros/utils/array_construct.sql
  tests/functional/adapter/utils/test_utils.py
Labels: cla:yes, ready_for_review

#274 CT-1166 test_aliases conversion
  tests/functional/adapter/test_aliases.py
  tests/integration/aliases_test/macros/cast.sql
  tests/integration/aliases_test/macros/expect_value.sql
  tests/integration/aliases_test/models/alias_in_project.sql
  tests/integration/aliases_test/models/alias_in_project_with_override.sql
  tests/integration/aliases_test/models/foo_alias.sql
  tests/integration/aliases_test/models/ref_foo_alias.sql
  tests/integration/aliases_test/models/schema.yml
  tests/integration/aliases_test/test_aliases.py
Labels: cla:yes, Skip Changelog

#273 consolidate timestamp macros
  .changes/unreleased/Feature-20220923-112314.yaml
  dbt/include/snowflake/macros/adapters.sql
  dbt/include/snowflake/macros/utils/timestamps.sql
  tests/functional/adapter/test_timestamps.py
Labels: cla:yes
