Repository dbt-labs/dbt-snowflake, pull requests merged in 2022-08, with the labels that each got.

#212 [Feature] add Changie to dbt-snowflake
  .changes/0.0.0.md
  .changes/1.3.0-b1.md
  .changes/1.3.0/Features-20220729-132848.yaml
  .changes/1.3.0/Under the Hood-20220729-132335.yaml
  .changes/1.3.0/Under the Hood-20220729-132559.yaml
  .changes/README.md
  .changes/header.tpl.md
  .changes/unreleased/.gitkeep
  .changes/unreleased/Under the Hood-20220803-093405.yaml
  .changie.yaml
  .github/pull_request_template.md
  .github/workflows/bot-changelog.yml
  .github/workflows/changelog-existence.yml
  CHANGELOG.md
  CONTRIBUTING.MD
Labels: cla:yes

#225 typos and ref changes for changie
  .changes/README.md
  .github/pull_request_template.md
  .github/workflows/changelog-existence.yml
Labels: cla:yes, Skip Changelog

#232 add test for column precision change
  tests/functional/adapter/test_incremental_run_result.py
Labels: cla:yes, Skip Changelog

#210 Feature/support query tags in tests
  .changes/unreleased/Features-20220815-233505.yaml
  dbt/include/snowflake/macros/materializations/test.sql
  tests/integration/query_tag_tests/models/models.yml
  tests/integration/query_tag_tests/test_query_tags.py
Labels: cla:yes, ready_for_review

#235 Test Conversion for Query Tag Tests
  tests/functional/query_tag/test_query_tags.py
  tests/integration/query_tag_tests/macros/check_tag.sql
  tests/integration/query_tag_tests/models/incremental_model_query_tag.sql
  tests/integration/query_tag_tests/models/models.yml
  tests/integration/query_tag_tests/models/table_model_query_tag.sql
  tests/integration/query_tag_tests/models/view_model_query_tag.sql
  tests/integration/query_tag_tests/seeds/seed_query_tag.csv
  tests/integration/query_tag_tests/snapshots/snapshot_query_tag.sql
  tests/integration/query_tag_tests/test_query_tags.py
Labels: cla:yes, Skip Changelog

#239 Shared version-bump and adding backport actions
  .github/workflows/backport.yml
  .github/workflows/version-bump.yml
Labels: cla:yes, Skip Changelog

#242 add supported language
  .changes/unreleased/Under the Hood-20220825-073653.yaml
  dbt/include/snowflake/macros/materializations/incremental.sql
  dbt/include/snowflake/macros/materializations/table.sql
Labels: cla:yes

#227 Add conditional logic for kinds in changie.yaml
  .changie.yaml
Labels: cla:yes, Skip Changelog

#207 connection retry refactor, add defaults with exponential backoff
  .changes/unreleased/Features-20220804-151121.yaml
  dbt/adapters/snowflake/connections.py
Labels: cla:yes

#93 Remove use of temp table for Snowflake incremental merge
  .changes/unreleased/Under the Hood-20220805-091724.yaml
  dbt/include/snowflake/macros/materializations/incremental.sql
  tests/integration/simple_copy_test/test_simple_copy.py
Labels: cla:yes, ok to test, test snowflake, ready_for_review

#246 fix getting schema and database for UDF
  .changes/unreleased/Fixes-20220830-172838.yaml
  dbt/adapters/snowflake/impl.py
Labels: cla:yes
