Repository dbt-labs/dbt-snowflake, pull requests merged in 2023-03, with the labels that each got.

#489 Standardize dev requirements
  .flake8
  .pre-commit-config.yaml
  Makefile
  dbt/adapters/snowflake/connections.py
  dev-requirements.txt
  setup.py
Labels: cla:yes, Skip Changelog

#496 Revert "Revert "mirror issues to ADAP jira project""
  .github/workflows/jira-creation.yml
  .github/workflows/jira-label.yml
  .github/workflows/jira-transition.yml
Labels: cla:yes, Skip Changelog

#484 implement data_type_code_to_name on SnowflakeConnectionManager
  .changes/unreleased/Features-20230223-182450.yaml
  dbt/adapters/snowflake/connections.py
  tests/functional/adapter/test_constraints.py
Labels: cla:yes

#476 CT-2112: bump snowflake connector python
  .changes/unreleased/Dependencies-20230216-093128.yaml
  .changes/unreleased/Dependencies-20230304-135458.yaml
  .dockerignore
  Makefile
  docker_dev/README.md
  docker_dev/debian.Dockerfile
  docker_dev/dev-env-default.Dockerfile
  docker_dev/ubuntu.Dockerfile
  setup.py
  tests/functional/adapter/simple_seed/test_simple_seed.py
  tests/functional/adapter/test_constraints.py
  tests/functional/oauth/test_oauth.py
Labels: cla:yes, backport 1.1.latest, backport 1.2.latest, backport 1.3.latest, backport 1.4.latest

#500 support contracts on models materialized as view
  .changes/unreleased/Features-20230223-182450.yaml
  dbt/include/snowflake/macros/adapters.sql
  tests/functional/adapter/test_constraints.py
Labels: cla:yes

#503 added macro for wh selection
  .changes/unreleased/Features-20230307-140933.yaml
  dbt/adapters/snowflake/impl.py
  dbt/include/snowflake/macros/etc.sql
Labels: cla:yes

#501 add new scripts for cut-release workflow
  .github/scripts/update_dependencies.sh
  .github/scripts/update_release_branch.sh
  .github/workflows/cut-release-branch.yml
Labels: cla:yes, Skip Changelog

#509 CT-2112: bump snowflake connector python (#476)
  .changes/unreleased/Dependencies-20230216-093128.yaml
  .changes/unreleased/Dependencies-20230304-135458.yaml
  setup.py
Labels: cla:yes

#508 CT-2112: bump snowflake connector python (#476)
  .changes/unreleased/Dependencies-20230216-093128.yaml
  .changes/unreleased/Dependencies-20230304-135458.yaml
  setup.py
Labels: cla:yes

#507 CT-2112: bump snowflake connector python (#476)
  .changes/unreleased/Dependencies-20230216-093128.yaml
  .changes/unreleased/Dependencies-20230304-135458.yaml
  setup.py
Labels: cla:yes

#506 CT-2112: bump snowflake connector python (#476)
  .changes/unreleased/Dependencies-20230216-093128.yaml
  .changes/unreleased/Dependencies-20230304-135458.yaml
  setup.py
Labels: cla:yes

#505 use single quotes in python models
  dbt/include/snowflake/macros/materializations/table.sql
Labels: cla:yes, Skip Changelog

#510 CT-1529 - Python 3.11 support (#354)
  .changes/unreleased/Features-20230130-122257.yaml
  .github/scripts/integration-test-matrix.js
  .github/workflows/main.yml
  setup.py
  tox.ini
Labels: cla:yes

#511 Fix change log entry for #476
  .changes/unreleased/Dependencies-20230216-093128.yaml
  .changes/unreleased/Security-20230216-093128.yaml
Labels: cla:yes, backport 1.1.latest, backport 1.2.latest, backport 1.3.latest, backport 1.4.latest

#515 Fix change log entry for #476 (#511)
  .changes/unreleased/Dependencies-20230216-093128.yaml
  .changes/unreleased/Security-20230216-093128.yaml
Labels: cla:yes

#514 Fix change log entry for #476 (#511)
  .changes/unreleased/Dependencies-20230216-093128.yaml
  .changes/unreleased/Security-20230216-093128.yaml
Labels: cla:yes

#513 Fix change log entry for #476 (#511)
  .changes/unreleased/Dependencies-20230216-093128.yaml
  .changes/unreleased/Security-20230216-093128.yaml
Labels: cla:yes

#512 Fix change log entry for #476 (#511)
  .changes/unreleased/Dependencies-20230216-093128.yaml
  .changes/unreleased/Security-20230216-093128.yaml
Labels: cla:yes

#517 Adds query_tag to the tuple returned by _connection_keys()
  .changes/unreleased/Fixes-20221215-234732.yaml
  dbt/adapters/snowflake/connections.py
  tests/unit/test_snowflake_adapter.py
Labels: cla:yes

#520 Fix deprecated GitHub action commands
  .changes/unreleased/Under the Hood-20221027-213024.yaml
  .github/workflows/bot-changelog.yml
  .github/workflows/changelog-existence.yml
  .github/workflows/integration.yml
  .github/workflows/main.yml
  .github/workflows/release-branch-tests.yml
  .github/workflows/stale.yml
  .github/workflows/version-bump.yml
Labels: cla:yes, Skip Changelog

#519 add triage-labels workflow
  .github/workflows/triage-labels.yml
Labels: cla:yes, Skip Changelog

#401 ADAP-281 - Raise warning, not error, for isolated `begin;` or `commit;`
  .changes/unreleased/Fixes-20230117-120349.yaml
  dbt/adapters/snowflake/connections.py
  tests/functional/test_isolated_begin_commit.py
Labels: cla:yes, ready_for_review, backport 1.2.latest, backport 1.3.latest, backport 1.4.latest, pr_tracked

#523 ADAP-281 - Raise warning, not error, for isolated `begin;` or `commit…
  .changes/unreleased/Fixes-20230117-120349.yaml
  dbt/adapters/snowflake/connections.py
  tests/functional/test_isolated_begin_commit.py
Labels: cla:yes

#525 ADAP-281 - Raise warning, not error, for isolated `begin;` or `commit…
  .changes/unreleased/Fixes-20230117-120349.yaml
  dbt/adapters/snowflake/connections.py
  tests/functional/test_isolated_begin_commit.py
Labels: cla:yes

#524 ADAP-281 - Raise warning, not error, for isolated `begin;` or `commit…
  .changes/unreleased/Fixes-20230117-120349.yaml
  dbt/adapters/snowflake/connections.py
  tests/functional/test_isolated_begin_commit.py
Labels: cla:yes

#521 Update create_table_as to use get_select_subquery for column ordering
  .changes/unreleased/Features-20230314-114033.yaml
  dbt/include/snowflake/macros/adapters.sql
  tests/functional/adapter/test_constraints.py
Labels: cla:yes

#522 Modify adapter to support unified constraint fields
  .changes/unreleased/Features-20230314-123129.yaml
  dbt/include/snowflake/macros/utils/get_columns_spec_ddl.sql
  tests/functional/adapter/test_constraints.py
Labels: cla:yes

#536 reverting #505
  .changes/1.5.0/Features-20230307-140933.yaml
  dbt/adapters/snowflake/impl.py
  dbt/include/snowflake/macros/etc.sql
Labels: cla:yes, Skip Changelog

#540 update to retrieve contract enforced from dict
  .changes/1.5.0/Under the Hood-20230223-104631.yaml
  .changes/unreleased/Under the Hood-20230223-104631.yaml
  dbt/include/snowflake/macros/adapters.sql
Labels: cla:yes

#542 Add the requirements file to what triggers an integration test build
  .github/workflows/integration.yml
Labels: cla:yes, Skip Changelog
