Repository dbt-labs/dbt-snowflake, pull requests merged in 2023-07, with the labels that each got.

#236 change on catalog.sql in case big information_schema
  .changes/unreleased/Features-20220816-081318.yaml
  dbt/include/snowflake/macros/catalog.sql
Labels: cla:yes, ready_for_review, pr_tracked

#684 implement new refresh logic, remove flaky workaround
  .changes/unreleased/Fixes-20230706-163838.yaml
  dbt/include/snowflake/macros/materializations/dynamic_table/ddl.sql
  tests/functional/adapter/dynamic_table_tests/fixtures.py
  tests/functional/adapter/dynamic_table_tests/test_dynamic_table.py
Labels: cla:yes

#686 update pr template
  .github/pull_request_template.md
Labels: Skip Changelog

#664 [Feature] dbt_clone sf implementation
  .changes/unreleased/Features-20230622-114621.yaml
  dbt/include/snowflake/macros/materializations/clone.sql
  tests/functional/adapter/dbt_clone/test_dbt_clone.py
Labels: cla:yes

#691 Apply new integration tests to existing framework to identify supported features
  .changes/unreleased/Features-20230714-224033.yaml
  Makefile
  dbt/adapters/snowflake/impl.py
  tests/functional/adapter/dynamic_table_tests/files.py
  tests/functional/adapter/dynamic_table_tests/fixtures.py
  tests/functional/adapter/dynamic_table_tests/test_dynamic_table.py
  tests/functional/adapter/dynamic_table_tests/test_dynamic_tables_basic.py
  tests/functional/adapter/dynamic_table_tests/test_dynamic_tables_changes.py
  tests/functional/adapter/dynamic_table_tests/utils.py
Labels: cla:yes

#690 add datadog env vars
  .github/workflows/integration.yml
  dev-requirements.txt
  tox.ini
Labels: cla:yes, Skip Changelog

#697 [Backport 1.6.latest] Add Datadog Env Vars
  .github/workflows/integration.yml
  dev-requirements.txt
  tox.ini
Labels: cla:yes, Skip Changelog

#698 [Backport 1.5.latest] Add Datadog Env Vars
  .github/workflows/integration.yml
  dev-requirements.txt
  tox.ini
Labels: cla:yes, Skip Changelog

#696 [Backport 1.4.latest] Add Datadog Env Vars
  .github/workflows/integration.yml
  dev-requirements.txt
  tox.ini
Labels: cla:yes, Skip Changelog

#695 [Backport 1.3.latest] Add Datadog Env Vars
  .github/workflows/integration.yml
  dev-requirements.txt
  tox.ini
Labels: cla:yes, Skip Changelog

#694 [Backport 1.2.latest] Add Datadog Env Vars
  .github/workflows/integration.yml
  dev-requirements.txt
  tox.ini
Labels: cla:yes, Skip Changelog

#671 fix: add option to use private key for authentication
  .changes/unreleased/Under the Hood-20230621-144450.yaml
  dbt/adapters/snowflake/connections.py
Labels: cla:yes, ready_for_review, pr_tracked

#707 Update stale workflow to use centralized version
  .changes/unreleased/Under the Hood-20230724-162947.yaml
  .github/workflows/stale.yml
Labels: cla:yes

#708 ADAP-728: Fix "On Configuration Change" config
  .changes/unreleased/Fixes-20230726-164729.yaml
  .flake8
  dbt/adapters/snowflake/relation.py
  dbt/adapters/snowflake/relation_configs/__init__.py
  dbt/adapters/snowflake/relation_configs/base.py
  dbt/adapters/snowflake/relation_configs/dynamic_table.py
  dbt/adapters/snowflake/relation_configs/policies.py
  dbt/adapters/snowflake/relation_configs/target_lag.py
  dbt/include/snowflake/macros/materializations/dynamic_table/ddl.sql
  dbt/include/snowflake/macros/materializations/dynamic_table/materialization.sql
  setup.py
  tests/functional/adapter/dynamic_table_tests/files.py
  tests/functional/adapter/dynamic_table_tests/test_dynamic_tables_changes.py
  tests/functional/adapter/dynamic_table_tests/utils.py
Labels: cla:yes, backport 1.6.latest
