Repository dbt-labs/dbt-snowflake, pull requests merged in 2023-01, with the labels that each got.

#377 update cryptography upperbound to avoid vulnerability
  .changes/unreleased/Dependencies-20230104-152808.yaml
  setup.py
Labels: cla:yes

#376 update cryptography upperbound to avoid vulnerability
  .changes/unreleased/Dependencies-20230104-151850.yaml
  setup.py
Labels: cla:yes

#375 Update cryptography upper bound.
  .changes/unreleased/Dependencies-20230104-151052.yaml
  setup.py
Labels: cla:yes

#372 [CT-1707] snowflake local testing fix
  .changes/unreleased/Under the Hood-20230106-161149.yaml
  setup.py
Labels: cla:yes

#378 Ct 443/strip sensitive data from logs
  .changes/unreleased/Under the Hood-20220920-172401.yaml
  dbt/adapters/snowflake/connections.py
  tests/functional/row_values_unlogged/test_row_values_not_in_exceptions.py
Labels: cla:yes, ready_for_review

#380 [CT-1771] Bugfix for tox above 4.0 backport so our test jobs work
  tox.ini
Labels: cla:yes, Skip Changelog

#381 [CT-1771] Add 1.3.latest to the scheduled test runs.
  .github/workflows/release-branch-tests.yml
Labels: cla:yes, Skip Changelog

#379 Have snowflake build incremental model optimized _tmp tables with temporary views.
  .changes/unreleased/Fixes-20230108-022919.yaml
  dbt/include/snowflake/macros/adapters.sql
  dbt/include/snowflake/macros/materializations/incremental.sql
Labels: cla:yes

#385 fix release.yml pypi steps
  .github/workflows/release.yml
Labels: cla:yes, Skip Changelog

#384 rename exceptions
  .changes/unreleased/Under the Hood-20230110-084413.yaml
  dbt/adapters/snowflake/column.py
  dbt/adapters/snowflake/connections.py
  dbt/adapters/snowflake/impl.py
  tests/integration/simple_reference_test/test_simple_reference.py
  tests/integration/simple_snapshot_test/test_simple_snapshot.py
  tests/integration/simple_snapshot_test/test_snapshot_check_cols.py
Labels: cla:yes

#392 Mp/reduce ci daily run intervals
  .github/workflows/main-branch-tests.yml
  .github/workflows/release-branch-tests.yml
Labels: cla:yes, Skip Changelog

#389 [CT-1507] create config for incremental models to use temp tables or views to fix regression in perf
  .changes/unreleased/Features-20230112-162620.yaml
  dbt/adapters/snowflake/impl.py
  dbt/include/snowflake/macros/materializations/incremental.sql
Labels: cla:yes

#398 Convert incremental on_schema_change tests
  tests/functional/adapter/incremental/test_incremental_on_schema_change.py
  tests/functional/adapter/incremental/test_incremental_predicates.py
  tests/functional/adapter/incremental/test_incremental_run_result.py
  tests/functional/adapter/incremental/test_incremental_unique_id.py
  tests/integration/incremental_schema_tests/models/incremental_append_new_columns.sql
  tests/integration/incremental_schema_tests/models/incremental_append_new_columns_remove_one.sql
  tests/integration/incremental_schema_tests/models/incremental_append_new_columns_remove_one_target.sql
  tests/integration/incremental_schema_tests/models/incremental_append_new_columns_target.sql
  tests/integration/incremental_schema_tests/models/incremental_fail.sql
  tests/integration/incremental_schema_tests/models/incremental_ignore.sql
  tests/integration/incremental_schema_tests/models/incremental_ignore_target.sql
  tests/integration/incremental_schema_tests/models/incremental_sync_all_columns.sql
  tests/integration/incremental_schema_tests/models/incremental_sync_all_columns_target.sql
  tests/integration/incremental_schema_tests/models/model_a.sql
  tests/integration/incremental_schema_tests/models/schema.yml
  tests/integration/incremental_schema_tests/test_incremental_schema.py
  tests/integration/incremental_schema_tests/tests/select_from_a.sql
  tests/integration/incremental_schema_tests/tests/select_from_incremental_append_new_columns.sql
  tests/integration/incremental_schema_tests/tests/select_from_incremental_append_new_columns_remove_one.sql
  tests/integration/incremental_schema_tests/tests/select_from_incremental_append_new_columns_remove_one_target.sql
  tests/integration/incremental_schema_tests/tests/select_from_incremental_append_new_columns_target.sql
  tests/integration/incremental_schema_tests/tests/select_from_incremental_ignore.sql
  tests/integration/incremental_schema_tests/tests/select_from_incremental_ignore_target.sql
  tests/integration/incremental_schema_tests/tests/select_from_incremental_sync_all_columns.sql
  tests/integration/incremental_schema_tests/tests/select_from_incremental_sync_all_columns_target.sql
Labels: cla:yes, Skip Changelog

#403 [CT-1507] part 2: Expand configuration to all strategies
  .changes/unreleased/Features-20230112-162620.yaml
  .changes/unreleased/Under the Hood-20230119-103909.yaml
  dbt/adapters/snowflake/impl.py
  dbt/include/snowflake/macros/materializations/incremental.sql
  tests/integration/simple_copy_test/test_simple_copy.py
Labels: cla:yes, Skip Changelog

#405 remove uneeded comma
  tests/integration/simple_copy_test/test_simple_copy.py
Labels: cla:yes, Skip Changelog

#399 Respect quoting in dbt-py models
  .changes/unreleased/Fixes-20230116-124031.yaml
  dbt/include/snowflake/macros/materializations/table.sql
  tests/functional/adapter/test_python_model.py
Labels: cla:yes

#383 enable SnowPark usage tracking
  .changes/unreleased/Under the Hood-20230120-110325.yaml
  dbt/adapters/snowflake/impl.py
Labels: cla:yes

#395 Convert caching_test
  tests/functional/adapter/test_caching.py
  tests/integration/caching_test/models/model.sql
  tests/integration/caching_test/shouting_models/MODEL.sql
  tests/integration/caching_test/test_caching.py
Labels: cla:yes, Skip Changelog

#415 add mypy exception
  dbt/adapters/snowflake/impl.py
Labels: cla:yes, Skip Changelog

#411 [CT-1630] Convert column_types test for dbt-snowflake
  tests/functional/adapter/column_types/fixtures.py
  tests/functional/adapter/column_types/test_column_types.py
  tests/integration/column_type_tests/macros/test_alter_column_type.sql
  tests/integration/column_type_tests/macros/test_is_type.sql
  tests/integration/column_type_tests/sf_models/model.sql
  tests/integration/column_type_tests/test_column_types.py
Labels: cla:yes, Skip Changelog

#409 Remove test for CT-1629 in dbt-core.
  tests/integration/column_quoting/models-unquoted/model.sql
  tests/integration/column_quoting/models/model.sql
  tests/integration/column_quoting/seeds/seed.csv
  tests/integration/column_quoting/test_column_quotes.py
Labels: cla:yes, Skip Changelog

#394 [CI/CD] Update release workflow and introduce workflow for nightly releases
  .bumpversion.cfg
  .github/workflows/nightly-release.yml
  .github/workflows/release.yml
  scripts/env-setup.sh
Labels: cla:yes, Skip Changelog

#414 Remove PR requirement from Changelog
  .changie.yaml
  .github/workflows/bot-changelog.yml
Labels: cla:yes, Skip Changelog

#421 [CI/CD] Update release workflow definition
  .github/workflows/release.yml
Labels: cla:yes, Skip Changelog

#416 Migrate persist docs to an adapter zone variant.
  tests/functional/adapter/test_persist_docs.py
  tests/integration/persist_docs_tests/models-column-missing/missing_column.sql
  tests/integration/persist_docs_tests/models-column-missing/schema.yml
  tests/integration/persist_docs_tests/models/my_fun_docs.md
  tests/integration/persist_docs_tests/models/no_docs_model.sql
  tests/integration/persist_docs_tests/models/schema.yml
  tests/integration/persist_docs_tests/models/table_model.sql
  tests/integration/persist_docs_tests/models/view_model.sql
  tests/integration/persist_docs_tests/seeds/seed.csv
  tests/integration/persist_docs_tests/test_persist_docs.py
Labels: cla:yes, Skip Changelog
