Repository dbt-labs/dbt-snowflake, pull requests merged in 2023-02, with the labels that each got.

#429 fix contributor issue list
  .changie.yaml
Labels: cla:yes, Skip Changelog

#420 [BACKPORT] Remove PR requirement from Changelog (#414)
  .changie.yaml
  .github/workflows/bot-changelog.yml
Labels: cla:yes, Skip Changelog

#419 [BACKPORT] Remove PR requirement from Changelog (#414)
  .changie.yaml
  .github/workflows/bot-changelog.yml
Labels: cla:yes, Skip Changelog

#418 [BACKPORT] Remove PR requirement from Changelog (#414)
  .changie.yaml
  .github/workflows/bot-changelog.yml
Labels: cla:yes, Skip Changelog

#417 [BACKPORT] Remove PR requirement from Changelog (#414)
  .changie.yaml
  .github/workflows/bot-changelog.yml
Labels: cla:yes, Skip Changelog

#442 Fix typo
  .changes/unreleased/Fixes-20230201-162407.yaml
  dbt/include/snowflake/macros/adapters.sql
Labels: cla:yes, ready_for_review, pr_tracked

#444 update regex for version bump
  .bumpversion.cfg
Labels: cla:yes, Skip Changelog

#445 update prerelease -> prekind
  .bumpversion.cfg
Labels: cla:yes, Skip Changelog

#427 [CI/CD] Backport release workflow to `1.4.latest`
  .bumpversion.cfg
  .github/workflows/nightly-release.yml
  .github/workflows/release.yml
  scripts/env-setup.sh
Labels: cla:yes, Skip Changelog

#447 rename dev_requirements to dev-requirements to match other branches
  .github/workflows/main.yml
  .github/workflows/version-bump.yml
  CONTRIBUTING.MD
  Makefile
  dev-requirements.txt
  tox.ini
Labels: cla:yes, Skip Changelog

#425 [CI/CD] Backport release workflow to `1.2.latest`
  .bumpversion.cfg
  .github/workflows/nightly-release.yml
  .github/workflows/release.yml
  scripts/env-setup.sh
Labels: cla:yes, Skip Changelog

#424 [CI/CD] Backport release workflow to `1.1.latest`
  .bumpversion.cfg
  .github/workflows/nightly-release.yml
  .github/workflows/release.yml
  scripts/env-setup.sh
Labels: cla:yes, Skip Changelog

#426 [CI/CD] Backport release workflow to `1.3.latest`
  .bumpversion.cfg
  .github/workflows/nightly-release.yml
  .github/workflows/release.yml
  scripts/env-setup.sh
Labels: cla:yes, Skip Changelog

#431 convert test_store_test_failures to functional test
  dev-requirements.txt
  tests/functional/adapter/store_test_failures_tests/test_store_test_failures.py
  tests/integration/store_test_failures_tests/models/fine_model.sql
  tests/integration/store_test_failures_tests/models/fine_model_but_with_a_no_good_very_long_name.sql
  tests/integration/store_test_failures_tests/models/problematic_model.sql
  tests/integration/store_test_failures_tests/models/schema.yml
  tests/integration/store_test_failures_tests/seeds/expected/expected_accepted_values.csv
  tests/integration/store_test_failures_tests/seeds/expected/expected_failing_test.csv
  tests/integration/store_test_failures_tests/seeds/expected/expected_not_null_problematic_model_id.csv
  tests/integration/store_test_failures_tests/seeds/expected/expected_unique_problematic_model_id.csv
  tests/integration/store_test_failures_tests/seeds/people.csv
  tests/integration/store_test_failures_tests/test_store_test_failures.py
  tests/integration/store_test_failures_tests/tests/failing_test.sql
  tests/integration/store_test_failures_tests/tests/passing_test.sql
Labels: cla:yes, tech_debt, Skip Changelog

#446 Remove unneeded tests. These are duplicate to the functional variant.
  tests/integration/column_comments_tests/models/quote_model.sql
  tests/integration/column_comments_tests/models/schema.yml
  tests/integration/column_comments_tests/test_column_comments.py
Labels: cla:yes, Skip Changelog

#428 Ct 854/change overzealous connection closing
  .changes/unreleased/Features-20230131-022659.yaml
  dbt/adapters/snowflake/connections.py
  tests/unit/test_snowflake_adapter.py
Labels: cla:yes, ready_for_review, pr_tracked

#448 [CT-2031]: Convert simple-seed to a functional test
  tests/functional/adapter/simple_seed/test_simple_seed.py
  tests/functional/adapter/simple_seed/test_simple_seed_override.py
  tests/integration/simple_seed_test/data-big/.gitignore
  tests/integration/simple_seed_test/macros/schema_test.sql
  tests/integration/simple_seed_test/models-snowflake/schema.yml
  tests/integration/simple_seed_test/seed.sql
  tests/integration/simple_seed_test/seeds-config/seed_disabled.csv
  tests/integration/simple_seed_test/seeds-config/seed_enabled.csv
  tests/integration/simple_seed_test/seeds-config/seed_tricky.csv
  tests/integration/simple_seed_test/test_seed_type_override.py
  tests/integration/simple_seed_test/test_simple_seed.py
Labels: cla:yes, Skip Changelog

#314 [CT-1485] Snowflake conversion of override_database
  tests/functional/override_database/test_override_database.py
  tests/integration/override_database_test/models/subfolder/view_3.sql
  tests/integration/override_database_test/models/subfolder/view_4.sql
  tests/integration/override_database_test/models/view_1.sql
  tests/integration/override_database_test/models/view_2.sql
  tests/integration/override_database_test/seeds/seed.csv
  tests/integration/override_database_test/test_override_database.py
Labels: cla:yes, Skip Changelog, pr_tracked

#455 [CT-1974]: convert statement_test to functional
  tests/functional/adapter/statement_test/seeds.py
  tests/functional/adapter/statement_test/test_statements.py
  tests/integration/statement_test/models/statement_actual.sql
  tests/integration/statement_test/snowflake-seed/statement_expected.csv
  tests/integration/statement_test/test_statements.py
Labels: cla:yes, Skip Changelog

#454 [CT-1970]: convert custom_schema tests to functional
  tests/functional/adapter/custom_schema_tests/seeds.py
  tests/functional/adapter/custom_schema_tests/test_custom_database.py
  tests/functional/adapter/custom_schema_tests/test_custom_schema.py
  tests/integration/custom_schema_test/custom-db-macros/custom_db.sql
  tests/integration/custom_schema_test/db-models/view_1.sql
  tests/integration/custom_schema_test/db-models/view_2.sql
  tests/integration/custom_schema_test/db-models/view_3.sql
  tests/integration/custom_schema_test/models/view_1.sql
  tests/integration/custom_schema_test/models/view_2.sql
  tests/integration/custom_schema_test/models/view_3.sql
  tests/integration/custom_schema_test/seed.sql
  tests/integration/custom_schema_test/test_custom_database.py
  tests/integration/custom_schema_test/test_custom_schema.py
Labels: cla:yes, Skip Changelog

#453 remove graph_selection test
  tests/integration/graph_selection_tests/.gitkeep
  tests/integration/graph_selection_tests/models/alternative.users.sql
  tests/integration/graph_selection_tests/models/base_users.sql
  tests/integration/graph_selection_tests/models/emails.sql
  tests/integration/graph_selection_tests/models/emails_alt.sql
  tests/integration/graph_selection_tests/models/never_selected.sql
  tests/integration/graph_selection_tests/models/schema.yml
  tests/integration/graph_selection_tests/models/test/subdir.sql
  tests/integration/graph_selection_tests/models/test/subdir/nested_users.sql
  tests/integration/graph_selection_tests/models/users.sql
  tests/integration/graph_selection_tests/models/users_rollup.sql
  tests/integration/graph_selection_tests/models/users_rollup_dependency.sql
  tests/integration/graph_selection_tests/seed.sql
  tests/integration/graph_selection_tests/test_graph_selection.py
Labels: cla:yes, Skip Changelog

#459 remove simple_reference integration test
  tests/integration/simple_reference_test/models/ephemeral_copy.sql
  tests/integration/simple_reference_test/models/ephemeral_summary.sql
  tests/integration/simple_reference_test/models/incremental_copy.sql
  tests/integration/simple_reference_test/models/incremental_summary.sql
  tests/integration/simple_reference_test/models/materialized_copy.sql
  tests/integration/simple_reference_test/models/materialized_summary.sql
  tests/integration/simple_reference_test/models/view_copy.sql
  tests/integration/simple_reference_test/models/view_summary.sql
  tests/integration/simple_reference_test/models/view_using_ref.sql
  tests/integration/simple_reference_test/seed.sql
  tests/integration/simple_reference_test/test_simple_reference.py
  tests/integration/simple_reference_test/update.sql
Labels: cla:yes, Skip Changelog

#206 add merge exclude tests -- use adapter zone test
  .changes/unreleased/Fixes-20230123-133059.yaml
  tests/functional/adapter/incremental/test_incremental_merge_exclude_columns.py
Labels: cla:yes, tech_debt, ready_for_review, pr_tracked

#397 Rm defer_state_test
  tests/integration/defer_state_test/macros/infinite_macros.sql
  tests/integration/defer_state_test/macros/macros.sql
  tests/integration/defer_state_test/models/ephemeral_model.sql
  tests/integration/defer_state_test/models/exposures.yml
  tests/integration/defer_state_test/models/schema.yml
  tests/integration/defer_state_test/models/table_model.sql
  tests/integration/defer_state_test/models/view_model.sql
  tests/integration/defer_state_test/seeds/seed.csv
  tests/integration/defer_state_test/test_defer_state.py
Labels: cla:yes, Skip Changelog, pr_tracked

#423 remove invocation of integration tests in tox
  .changes/unreleased/Under the Hood-20230130-171247.yaml
  CONTRIBUTING.md
  tox.ini
Labels: cla:yes, tech_debt

#451 parse vars in unit test utils
  tests/unit/utils.py
Labels: cla:yes, Skip Changelog

#430 Sync Changelog team to GitHub team
  .bumpversion.cfg
  .changie.yaml
Labels: cla:yes, Skip Changelog

#466 Ct 2106 update cryptography dependency
  .changes/unreleased/Dependencies-20230213-174442.yaml
  setup.py
Labels: cla:yes, ready_for_review

#472 Bump upper bound of `snowflake-connector-python`
  .changes/unreleased/Dependencies-20230216-093128.yaml
  setup.py
Labels: cla:yes, ready_for_review

#370 Remove dead code from test utils
  .changes/unreleased/Fixes-20221221-063703.yaml
  tests/unit/utils.py
Labels: cla:yes, ready_for_review, pr_tracked

#473 Revert "Bump upper bound of `snowflake-connector-python`"
  .changes/unreleased/Dependencies-20230216-093128.yaml
  setup.py
Labels: cla:yes, Skip Changelog

#475 release test based off 1.4
  .bumpversion.cfg
  .github/workflows/nightly-release.yml
  setup.py
Labels: cla:yes, Skip Changelog

#470 add new workflow for cutting .latest branches
  .github/workflows/cut-release-branch.yml
Labels: cla:yes, Skip Changelog

#478 Fix nightly release test
  .bumpversion.cfg
  .github/workflows/nightly-release.yml
  setup.py
Labels: cla:yes, Skip Changelog

#481 fixed changie logs for 1.5.0b1 release
  .changes/unreleased/Dependencies-20230213-174442.yaml
  .changes/unreleased/Features-20230131-022659.yaml
  .changes/unreleased/Fixes-20230201-162407.yaml
  .changes/unreleased/Under the Hood-20230130-171247.yaml
Labels: cla:yes

#457 Fix unset query tag in view materialization
  .changes/unreleased/Fixes-20230208-210326.yaml
  dbt/include/snowflake/macros/materializations/view.sql
Labels: cla:yes, ready_for_review

#483 Rename "constraints_enabled" to "contract"
  .changes/unreleased/Under the Hood-20230223-104631.yaml
  dbt/include/snowflake/macros/adapters.sql
Labels: cla:yes

#292 Add key-pair auth with private key in environment variable
  .changes/unreleased/Features-20221011-133105.yaml
  dbt/adapters/snowflake/connections.py
  tests/unit/test_snowflake_adapter.py
Labels: cla:yes, ready_for_review, pr_tracked

#460 mirror issues to ADAP jira project
  .github/workflows/jira-creation.yml
  .github/workflows/jira-label.yml
  .github/workflows/jira-transition.yml
Labels: cla:yes, Skip Changelog

#488 Revert "mirror issues to ADAP jira project"
  .github/workflows/jira-creation.yml
  .github/workflows/jira-label.yml
  .github/workflows/jira-transition.yml
Labels: cla:yes
