Repository dbt-labs/dbt-snowflake, pull requests merged in 2023-09, with the labels that each got.

#763 update expected values
  .changes/unreleased/Fixes-20230907-153305.yaml
  tests/functional/adapter/expected_stats.py
Labels: cla:yes

#770 bug/Dynamic-table-comment-on-syntax
  .changes/unreleased/Fixes-20230914-110800.yaml
  dbt/include/snowflake/macros/adapters.sql
Labels: cla:yes, ok to test, test all

#775 Backport: bug/Dynamic-table-comment-on-syntax (#770)
  .changes/unreleased/Fixes-20230914-110800.yaml
  dbt/include/snowflake/macros/adapters.sql
Labels: cla:yes

#778 remove broken flake8
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#771 allow testing against any core branch
  .github/scripts/update_dbt_core_branch.sh
  .github/workflows/integration.yml
Labels: cla:yes, Skip Changelog

#781 [Backport 1.5.latest] Redact values from logs due 'duplicate key' error
  .changes/unreleased/Features-20230915-091507.yaml
  dbt/adapters/snowflake/connections.py
  tests/functional/redact_log_values/test_duplicate_key_not_in_exceptions.py
  tests/functional/redact_log_values/test_row_values_not_in_exceptions.py
Labels: cla:yes

#782 [Backport 1.6.latest] Redact values from logs due 'duplicate key' error
  .changes/unreleased/Features-20230915-091507.yaml
  dbt/adapters/snowflake/connections.py
  tests/functional/redact_log_values/test_duplicate_key_not_in_exceptions.py
  tests/functional/redact_log_values/test_row_values_not_in_exceptions.py
Labels: cla:yes

#789 automate repo cleanup
  .github/workflows/repository-cleanup.yml
Labels: cla:yes, Skip Changelog

#768 Add debug logging
  .changes/unreleased/Under the Hood-20230925-120144.yaml
  dbt/adapters/snowflake/connections.py
  tests/unit/test_connections.py
Labels: cla:yes

#779 add dbt show tests
  .changes/unreleased/Under the Hood-20230925-144814.yaml
  tests/functional/adapter/dbt_show/test_dbt_show.py
Labels: cla:yes, backport 1.5.latest, backport 1.6.latest
