Repository dbt-labs/dbt-snowflake, pull requests merged in 2023-08, with the labels that each got.

#717 Mcknight/fix python model test
  tests/functional/adapter/test_python_model.py
Labels: cla:yes, Skip Changelog

#685 Move Alerts
  .github/workflows/main-branch-tests.yml
  .github/workflows/release.yml
Labels: cla:yes, Skip Changelog

#673 [ADAP-620] [Bug] Incremental materialization with "append" strategy does not wrap dml with explicit transaction
  .changes/unreleased/Fixes-20230626-132631.yaml
  dbt/include/snowflake/macros/materializations/merge.sql
Labels: cla:yes, test all

#716 Update connections.py so it doesn’t run anything after its canceled
  .changes/unreleased/Fixes-20230804-175222.yaml
  dbt/adapters/snowflake/connections.py
  tests/unit/test_snowflake_adapter.py
Labels: cla:yes

#727 [ADAP-774] fix snowflake_warehouse issue with dynamic tables
  dbt/adapters/snowflake/relation.py
  dbt/adapters/snowflake/relation_configs/dynamic_table.py
  dbt/include/snowflake/macros/materializations/dynamic_table/ddl.sql
Labels: cla:yes, Skip Changelog

#739 ADAP-796: Add datadog env vars to tox.ini
  tox.ini
Labels: cla:yes, Skip Changelog

#738 [Backport 1.6.latest] Update connections.py so it doesn’t run anything after its canceled
  .changes/unreleased/Fixes-20230804-175222.yaml
  dbt/adapters/snowflake/connections.py
  tests/unit/test_snowflake_adapter.py
Labels: cla:yes

#732 [ADAP-631] Convert Target_lag to str type to add Downstream option
  .changes/unreleased/Fixes-20230810-154613.yaml
  .changes/unreleased/Fixes-20230810-163232.yaml
  dbt/adapters/snowflake/relation_configs/__init__.py
  dbt/adapters/snowflake/relation_configs/dynamic_table.py
  dbt/adapters/snowflake/relation_configs/target_lag.py
  tests/functional/adapter/dynamic_table_tests/test_dynamic_tables_changes.py
Labels: cla:yes

#747 [Backport] set target_lag to a str to allow for 'downstream' as accepted value
  .changes/unreleased/Fixes-20230810-154613.yaml
  .changes/unreleased/Fixes-20230810-163232.yaml
  dbt/adapters/snowflake/relation_configs/__init__.py
  dbt/adapters/snowflake/relation_configs/dynamic_table.py
  dbt/adapters/snowflake/relation_configs/target_lag.py
  tests/functional/adapter/dynamic_table_tests/test_dynamic_tables_changes.py
Labels: cla:yes

#751 ADAP-821: Refactor prep for dynamic table / table/view swap
  .changes/unreleased/Under the Hood-20230821-230921.yaml
  dbt/include/snowflake/macros/adapters.sql
  dbt/include/snowflake/macros/materializations/dynamic_table.sql
  dbt/include/snowflake/macros/materializations/dynamic_table/ddl.sql
  dbt/include/snowflake/macros/relations/drop.sql
  dbt/include/snowflake/macros/relations/dynamic_table/_replace.sql
  dbt/include/snowflake/macros/relations/dynamic_table/alter.sql
  dbt/include/snowflake/macros/relations/dynamic_table/create.sql
  dbt/include/snowflake/macros/relations/dynamic_table/describe.sql
  dbt/include/snowflake/macros/relations/dynamic_table/drop.sql
  dbt/include/snowflake/macros/relations/dynamic_table/refresh.sql
  dbt/include/snowflake/macros/relations/rename.sql
  dbt/include/snowflake/macros/relations/table/create.sql
  dbt/include/snowflake/macros/relations/view/create.sql
Labels: cla:yes

#756 [ADAP-849] removes some user connection details from stdout
  .changes/unreleased/Fixes-20230828-143834.yaml
  dbt/adapters/snowflake/connections.py
Labels: cla:yes, Skip Changelog
