Repository dbt-labs/dbt-snowflake, pull requests merged in 2023-10, with the labels that each got.

#797 test against 1.7.latest release branch and fix semve
  .github/workflows/nightly-release.yml
Labels: cla:yes, Skip Changelog

#787 Add tests for `date_spine` macro, and sub macros
  tests/functional/adapter/utils/test_utils.py
Labels: cla:yes, Skip Changelog

#790 Bug/dynamic table alter on column syntax
  .changes/unreleased/Fixes-20231002-144648.yaml
  dbt/include/snowflake/macros/adapters.sql
Labels: cla:yes, ok to test

#783 ADAP-893: Support test results as views
  .changes/unreleased/Features-20230919-171047.yaml
  tests/functional/adapter/store_test_failures_tests/test_store_test_failures.py
Labels: cla:yes

#798 Remove manual refresh on dynamic table create
  .changes/unreleased/Under the Hood-20231010-182904.yaml
  dbt/include/snowflake/macros/relations/dynamic_table/create.sql
Labels: cla:yes

#758 ADAP-865: Parameterize where clause, add option to supply list of relations
  .changes/unreleased/Features-20230829-152412.yaml
  dbt/adapters/snowflake/impl.py
  dbt/include/snowflake/macros/catalog.sql
Labels: cla:yes

#802 Respect `transient` config for dbt Python models
  .changes/unreleased/Fixes-20230918-105721.yaml
  dbt/include/snowflake/macros/materializations/table.sql
  dbt/include/snowflake/macros/relations/table/create.sql
  tests/functional/adapter/python_model_tests/_files.py
  tests/functional/adapter/python_model_tests/test_table_type.py
Labels: cla:yes

#796 Implementation of metadata-based freshness
  .changes/unreleased/Features-20231008-195410.yaml
  dbt/adapters/snowflake/impl.py
  dbt/include/snowflake/macros/metadata.sql
  tests/functional/adapter/test_get_last_relation_modified.py
  tests/functional/adapter/test_list_relations_without_caching.py
Labels: cla:yes

#805 add doc-issues to dbt-snowflake
  .github/workflows/docs-issues.yml
Labels: cla:yes, Skip Changelog

#813 Unskip source freshness test that was skipped during troubleshooting
  tests/functional/adapter/test_get_last_relation_modified.py
Labels: Skip Changelog

#818 ADAP-971: Fix issue where dynamic tables were returning null for type
  .changes/unreleased/Fixes-20231030-212151.yaml
  dbt/include/snowflake/macros/catalog.sql
  tests/functional/adapter/catalog_tests/files.py
  tests/functional/adapter/catalog_tests/test_relation_types.py
Labels: cla:yes, backport 1.6.latest, backport 1.7.latest

#820 [Backport 1.6.latest] ADAP-971: Fix issue where dynamic tables were returning null for type
  .changes/unreleased/Fixes-20231030-212151.yaml
  dbt/include/snowflake/macros/catalog.sql
  tests/functional/adapter/catalog_tests/files.py
  tests/functional/adapter/catalog_tests/test_relation_types.py
Labels: cla:yes
