Repository dbt-labs/dbt-snowflake, pull requests merged in 2023-05, with the labels that each got.

#584 Fix for changie that pointed to spark
  .changie.yaml
Labels: cla:yes, Skip Changelog

#582 Fix Issue URLs in 1.5.0 Changelog
  .changie.yaml
  CHANGELOG.md
Labels: cla:yes, Skip Changelog

#580 update used gh actions ahead of set-output, node12 deprecation
  .github/workflows/integration.yml
  .github/workflows/main-branch-tests.yml
  .github/workflows/main.yml
  .github/workflows/release-branch-tests.yml
Labels: cla:yes, Skip Changelog

#609 [Backport] GitHub deprecations 1.5.latest
  .github/workflows/integration.yml
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#610 [Backport] 1.4.latest GitHub deprecation
  .github/workflows/integration.yml
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#611 [Backport] 1.3.latest GitHub deprecation
  .github/workflows/integration.yml
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#612 [Backport] 1.2.latest gh deprecations
  .github/workflows/integration.yml
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#614 [Backport] 1.1.latest gh deprecations
  .github/workflows/integration.yml
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#613 [Backport] 1.0.latest github deprecations
  .github/workflows/integration.yml
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#617 update used gh actions ahead of node12 deprecation
  .github/workflows/backport.yml
  .github/workflows/bot-changelog.yml
  .github/workflows/integration.yml
  .github/workflows/main-branch-tests.yml
  .github/workflows/main.yml
  .github/workflows/release-branch-tests.yml
Labels: cla:yes, Skip Changelog

#618 Custom schema must be picked up for all models
  .changes/unreleased/Fixes-20230518-011334.yaml
  dbt/include/snowflake/macros/materializations/table.sql
  tests/functional/adapter/test_python_model.py
Labels: cla:yes, backport 1.3.latest, backport 1.4.latest, backport 1.5.latest

#623 Backport #618
  .changes/unreleased/Fixes-20230518-011334.yaml
  dbt/include/snowflake/macros/materializations/table.sql
  tests/functional/adapter/test_python_model.py
Labels: cla:yes

#624 Backport #618
  .changes/unreleased/Fixes-20230518-011334.yaml
  dbt/include/snowflake/macros/materializations/table.sql
  tests/functional/adapter/test_python_model.py
Labels: cla:yes

#631 add missing space to dependabot changelog
  .github/workflows/bot-changelog.yml
Labels: cla:yes, Skip Changelog

#620 Convert release branch tests to use shared workflow
  .github/workflows/release-branch-tests.yml
  .github/workflows/triage-labels.yml
Labels: cla:yes, Skip Changelog

#588 fix regular expression for redaction of row values
  .changes/unreleased/Fixes-20230508-224927.yaml
  dbt/adapters/snowflake/connections.py
Labels: cla:yes, ready_for_review, pr_tracked

#637 Dropped support for Python 3.7
  .changes/unreleased/Under the Hood-20230530-161341.yaml
  .github/scripts/integration-test-matrix.js
  .github/workflows/main.yml
  .github/workflows/nightly-release.yml
  CONTRIBUTING.md
  dev-requirements.txt
  setup.py
  tox.ini
Labels: cla:yes

#641 [BACKPORT] regular expression change fix for newlines
  .changes/unreleased/Fixes-20230508-224927.yaml
  dbt/adapters/snowflake/connections.py
Labels: cla:yes, Skip Changelog

#646 swap alt database testing env
  tests/integration/override_database_test/test_override_database.py
Labels: cla:yes, Skip Changelog

#645 swap alt database testing env
  tests/integration/override_database_test/test_override_database.py
Labels: cla:yes, Skip Changelog

#643 change alt database testing env
  tests/integration/override_database_test/test_override_database.py
Labels: cla:yes, Skip Changelog

#627 adding link to 1.5 release notes
  .changes/0.0.0.md
  CHANGELOG.md
Labels: cla:yes, Skip Changelog
