Repository dbt-labs/dbt-snowflake, pull requests merged in 2024-02, with the labels that each got.

#895 install dbt-tests-adapter from dbt-adapters
  dev-requirements.txt
Labels: cla:yes, Skip Changelog

#901 Remove actions that sync github and jira
  .github/workflows/jira-creation.yml
  .github/workflows/jira-label.yml
  .github/workflows/jira-transition.yml
Labels: cla:yes, Skip Changelog, support

#906 remove token from _connection_keys
  .changes/unreleased/Fixes-20240216-125014.yaml
  dbt/adapters/snowflake/connections.py
Labels: cla:yes

#916 update dbt-common dependency to <2.0
  setup.py
Labels: cla:yes, Skip Changelog
