Repository dbt-labs/dbt-snowflake, pull requests merged in 2024-05, with the labels that each got.

#1012 Revert "Prefix secrets with DBT_ENV_SECRET_ for test env vars"
  .changes/unreleased/Under the Hood-20240425-153022.yaml
  .github/workflows/integration.yml
  scripts/werkzeug-refresh-token.py
  test.env.example
  tests/conftest.py
  tests/functional/oauth/test_oauth.py
  tox.ini
Labels: cla:yes, Skip Changelog

#1018 Remove field.
  tests/functional/adapter/dbt_clone/test_dbt_clone.py
Labels: cla:yes, Skip Changelog

#1026 Update CODEOWNERS
  .github/CODEOWNERS
Labels: cla:yes, Skip Changelog

#996 Move to `pre-commit` only
  .flake8
  .github/workflows/main.yml
  .pre-commit-config.yaml
  Makefile
  dbt/adapters/snowflake/__init__.py
  dbt/adapters/snowflake/connections.py
  dbt/adapters/snowflake/impl.py
  dbt/adapters/snowflake/relation.py
  dbt/adapters/snowflake/relation_configs/base.py
  dbt/adapters/snowflake/relation_configs/dynamic_table.py
  dev-requirements.txt
  mypy.ini
  tests/unit/utils.py
Labels: cla:yes, Skip Changelog

#1025 Update dev-requirements.txt to use common@main
  dev-requirements.txt
Labels: cla:yes, Skip Changelog

#982 Speedup catalog string comparison by using ilike before equals
  .changes/unreleased/Under the Hood-20240425-144556.yaml
  dbt/include/snowflake/macros/catalog.sql
Labels: cla:yes

#1011 Cross-database `date` macro
  .changes/unreleased/Features-20240501-151901.yaml
  tests/functional/adapter/utils/test_utils.py
Labels: cla:yes

#1010 Import relevant pytest(s) for cross-database `cast` macro
  .changes/unreleased/Features-20240430-185714.yaml
  tests/functional/adapter/utils/test_utils.py
Labels: cla:yes

#1039 Bump deps on common, adapters, core
  setup.py
Labels: cla:yes, Skip Changelog, backport 1.8.latest

#1029 update test_anonymous_usage_stats.py
  tests/functional/adapter/test_anonymous_usage_stats.py
Labels: cla:yes, Skip Changelog

#1044 remove duplicate package version and avoid bumping dbt-core version
  .bumpversion.cfg
  setup.py
Labels: cla:yes, Skip Changelog

#1045 remove duplicate package version and avoid bumping dbt-core version (#1044)
  .bumpversion.cfg
  setup.py
Labels: cla:yes, Skip Changelog

#1049 [Bug] Update `list_relations_without_caching` to support Snowflake bundle `2024_03`
  .changes/unreleased/Fixes-20240516-174337.yaml
  dbt/adapters/snowflake/impl.py
  dbt/include/snowflake/macros/adapters.sql
  tests/functional/adapter/list_relations_tests/test_pagination.py
  tests/functional/adapter/list_relations_tests/test_show_objects.py
Labels: cla:yes

#1056 [Backport 1.8.latest] Dynamic tables with Snowflake change bundle 2024_03 results in dynamic table to issue
  .changes/unreleased/Fixes-20240516-174337.yaml
  dbt/adapters/snowflake/impl.py
  dbt/include/snowflake/macros/adapters.sql
  tests/functional/adapter/list_relations_tests/test_pagination.py
  tests/functional/adapter/list_relations_tests/test_show_objects.py
Labels: cla:yes

#1050 Improve the memory efficiency of process_results() override
  .changes/unreleased/Under the Hood-20240517-143743.yaml
  dbt/adapters/snowflake/connections.py
Labels: cla:yes

#1057 [Backport 1.7.latest] Dynamic tables with Snowflake change bundle 2024_03 results in dynamic table to issue
  .changes/unreleased/Fixes-20240516-174337.yaml
  dbt/adapters/snowflake/impl.py
  dbt/include/snowflake/macros/adapters.sql
  tests/functional/adapter/list_relations_tests/test_pagination.py
  tests/functional/adapter/list_relations_tests/test_show_objects.py
Labels: cla:yes
