Repository dbt-labs/dbt-snowflake, pull requests merged in 2024-04, with the labels that each got.

#964 Add `dbt-core~=1.8.0a1` as convenience dep
  .changes/unreleased/Dependencies-20240403-133936.yaml
  setup.py
Labels: cla:yes

#955 Add external_access_integration and secret to python model impl
  .changes/unreleased/Features-20240402-131330.yaml
  dbt/adapters/snowflake/impl.py
  tests/functional/adapter/test_python_model.py
Labels: cla:yes, ok to test

#963 Add docker release to the full release process
  .github/dependabot.yml
  .github/workflows/release.yml
  Makefile
  docker/Dockerfile
  docker/README.md
  docker/dev.Dockerfile
  docker/test.sh
  docker_dev/README.md
  docker_dev/debian.Dockerfile
  docker_dev/dev-env-default.Dockerfile
  docker_dev/ubuntu.Dockerfile
Labels: cla:yes, Skip Changelog

#928 add Capability.TableLastModifiedMetadataBatch support
  .changes/unreleased/Features-20240404-171704.yaml
  dbt/adapters/snowflake/impl.py
  tests/functional/adapter/test_get_last_relation_modified.py
Labels: cla:yes

#981 Add dbt-core pre-commit check
  .pre-commit-config.yaml
  tests/unit/test_snowflake_adapter.py
Labels: cla:yes, Skip Changelog

#980 Stop adding aliases to render_limited output
  .changes/unreleased/Fixes-20240418-160240.yaml
  dbt/adapters/snowflake/relation.py
  tests/functional/adapter/empty/test_empty.py
Labels: cla:yes

#978 Docker automation tweak
  .github/workflows/nightly-release.yml
  .github/workflows/release.yml
Labels: cla:yes, Skip Changelog

#984 Update Dockerfile
  docker/Dockerfile
Labels: Skip Changelog

#985 Pin `macos` test runners to `macos-12`
  .github/scripts/integration-test-matrix.js
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#994 [Backport 1.0.latest] Pin `macos` runners to `macos-12` (#985)
  .github/scripts/integration-test-matrix.js
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#989 [Backport 1.5.latest] Pin `macos` runners to `macos-12` (#985)
  .github/scripts/integration-test-matrix.js
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#990 [Backport 1.4.latest] Pin `macos` runners to `macos-12` (#985)
  .github/scripts/integration-test-matrix.js
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#992 [Backport 1.2.latest] Pin `macos` runners to `macos-12` (#985)
  .github/scripts/integration-test-matrix.js
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#991 [Backport 1.3.latest] Pin `macos` runners to `macos-12` (#985)
  .github/scripts/integration-test-matrix.js
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#993 [Backport 1.1.latest] Pin `macos` runners to `macos-12` (#985)
  .github/scripts/integration-test-matrix.js
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#987 [Backport 1.7.latest] Pin `macos` runners to `macos-12` (#985)
  .github/scripts/integration-test-matrix.js
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#988 [Backport 1.6.latest] Pin `macos` runners to `macos-12` (#985)
  .github/scripts/integration-test-matrix.js
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#995 Prefix secrets with DBT_ENV_SECRET_ for test env vars
  .changes/unreleased/Under the Hood-20240425-153022.yaml
  .github/workflows/integration.yml
  scripts/werkzeug-refresh-token.py
  test.env.example
  tests/conftest.py
  tests/functional/oauth/test_oauth.py
  tox.ini
Labels: cla:yes

#1008 Update pin for `dbt-adapters` as reflected in #928
  setup.py
Labels: cla:yes, Skip Changelog
