Repository dbt-labs/dbt-snowflake, pull requests merged in 2024-10, with the labels that each got.

#1197 Update database role tests to avoid colliding with parallel test runs
  tests/functional/auth_tests/test_database_role.py
Labels: cla:yes, Skip Changelog

#1201 Fix Dynamic Iceberg Table Required DDL Params
  .changes/unreleased/Fixes-20241008-122635.yaml
  dbt/adapters/snowflake/relation_configs/catalog.py
  dbt/include/snowflake/macros/relations/dynamic_table/create.sql
  dbt/include/snowflake/macros/relations/dynamic_table/replace.sql
  tests/functional/iceberg/models.py
  tests/functional/iceberg/test_table_basic.py
Labels: cla:yes

#1212 Add query tag back to incremental models
  dbt/include/snowflake/macros/materializations/incremental.sql
  tests/functional/query_tag/test_query_tags.py
Labels: cla:yes, Skip Changelog, pre-regression

#1211 Drop support for Python 3.8
  .changes/unreleased/Breaking Changes-20241016-183143.yaml
  .github/scripts/integration-test-matrix.js
  .github/workflows/main.yml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  Makefile
  dev-requirements.txt
  docker/Dockerfile
  docker/dev.Dockerfile
  setup.py
  tox.ini
Labels: cla:yes

#1216 [Backport 1.8.latest] Drop support for Python 3.8
  .changes/unreleased/Breaking Changes-20241016-183143.yaml
  .github/scripts/integration-test-matrix.js
  .github/workflows/main.yml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  Makefile
  setup.py
  tox.ini
Labels: cla:yes

#1221 [Backport 1.4.latest] Drop support for Python 3.8
  .changes/unreleased/Breaking Changes-20241016-183143.yaml
  .github/scripts/integration-test-matrix.js
  .github/workflows/main.yml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  Makefile
  setup.py
  tox.ini
Labels: cla:yes

#1220 [Backport 1.5.latest] Drop support for Python 3.8
  .changes/unreleased/Breaking Changes-20241016-183143.yaml
  .github/scripts/integration-test-matrix.js
  .github/workflows/main.yml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  Makefile
  setup.py
  tox.ini
Labels: cla:yes

#1219 [Backport 1.6.latest] Drop support for Python 3.8
  .changes/unreleased/Breaking Changes-20241016-183143.yaml
  .github/scripts/integration-test-matrix.js
  .github/workflows/main.yml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  Makefile
  setup.py
  tox.ini
Labels: cla:yes

#1218 [Backport 1.7.latest] Drop support for Python 3.8
  .changes/unreleased/Breaking Changes-20241016-183143.yaml
  .github/scripts/integration-test-matrix.js
  .github/workflows/main.yml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  Makefile
  setup.py
  tox.ini
Labels: cla:yes

#1222 Add url.
  dbt/include/snowflake/macros/relations/table/create.sql
Labels: cla:yes, Skip Changelog

#1209 Add snowflake telemetry.
  .changes/unreleased/Under the Hood-20241016-035544.yaml
  dbt/adapters/snowflake/impl.py
  dev-requirements.txt
  setup.py
  tests/unit/test_adapter_telemetry.py
Labels: cla:yes

#1225 Revert requirements.
  dev-requirements.txt
  setup.py
Labels: cla:yes, Skip Changelog

#1172 Add test cases for generic tests config
  tests/functional/generic_test_tests/__init__.py
  tests/functional/generic_test_tests/_files.py
  tests/functional/generic_test_tests/_models.py
  tests/functional/generic_test_tests/_schemas.py
  tests/functional/generic_test_tests/test_generic_tests.py
Labels: cla:yes, Skip Changelog
