Repository dbt-labs/dbt-snowflake, pull requests merged in 2024-06, with the labels that each got.

#1067 replace underscores with hyphens in account ids
  .changes/unreleased/Features-20240604-154856.yaml
  dbt/adapters/snowflake/connections.py
  tests/unit/test_connections.py
  tests/unit/test_snowflake_adapter.py
Labels: cla:yes

#1075 quoting config not working with 1.8
  .changes/unreleased/Fixes-20240607-102708.yaml
  dbt/include/snowflake/macros/adapters.sql
  tests/functional/adapter/list_relations_tests/test_pagination.py
  tests/functional/adapter/list_relations_tests/test_special_characters.py
Labels: cla:yes

#1077 Update nightly-release.yml to use 1.8.latest
  .github/workflows/nightly-release.yml
Labels: cla:yes, Skip Changelog

#1078 [ENTERPRISE-1418] Add support for plain JWT authentication
  .changes/unreleased/Features-20240610-171026.yaml
  dbt/adapters/snowflake/connections.py
  tests/functional/oauth/test_jwt.py
  tests/unit/test_snowflake_adapter.py
Labels: cla:yes

#1080 Skip with reason dynamic table tests with reference to PR.
  tests/functional/adapter/dynamic_table_tests/test_dynamic_tables_changes.py
Labels: cla:yes, Skip Changelog

#1063 Adap 953/merge agate lazy load
  .changes/unreleased/Under the Hood-20240327-001304.yaml
  dbt/adapters/snowflake/connections.py
  dbt/adapters/snowflake/impl.py
  dbt/adapters/snowflake/relation_configs/base.py
  dbt/adapters/snowflake/relation_configs/dynamic_table.py
Labels: cla:yes

#1083 add retry to reduce flakiness of TestSecrets
  tests/functional/adapter/test_python_model.py
Labels: cla:yes, Skip Changelog

#1085 [Tech Debt] Fix dynamic table tests
  .changes/unreleased/Under the Hood-20240614-170858.yaml
  tests/functional/adapter/dynamic_table_tests/files.py
  tests/functional/adapter/dynamic_table_tests/test_dynamic_tables_changes.py
  tests/functional/adapter/dynamic_table_tests/utils.py
Labels: cla:yes

#1060 [Bug] Use fully qualified names in rename for tables and views
  .changes/unreleased/Fixes-20240522-160538.yaml
  dbt/include/snowflake/macros/relations/create_backup.sql
  dbt/include/snowflake/macros/relations/rename_intermediate.sql
  dbt/include/snowflake/macros/relations/table/rename.sql
  dbt/include/snowflake/macros/relations/view/rename.sql
  tests/functional/relation_tests/base.py
  tests/functional/relation_tests/test_table.py
  tests/functional/relation_tests/test_view.py
Labels: cla:yes

#1088 update user docs-issue workflow
  .github/workflows/docs-issues.yml
Labels: cla:yes, Skip Changelog

#1091 Update internal release naming and arguments
  .github/workflows/release-internal.yml
Labels: cla:yes, test all, Skip Changelog

#1092 Expand file filter for triggering integration tests
  .github/workflows/integration.yml
Labels: cla:yes, Skip Changelog

#1064 Implement `get_catalog_for_single_relation` macro
  .changes/unreleased/Fixes-20240516-224134.yaml
  .gitignore
  dbt/adapters/snowflake/impl.py
  dbt/include/snowflake/macros/adapters.sql
  setup.py
  tests/functional/adapter/test_basic.py
  tests/unit/mock_adapter.py
Labels: cla:yes

#1072 [Bug] Silent SSO token expiration
  .changes/unreleased/Fixes-20240605-125611.yaml
  dbt/adapters/snowflake/connections.py
  tests/functional/oauth/test_oauth.py
  tests/unit/test_connections.py
Labels: cla:yes

#1096 `test_python_model.py::TestSecrets::test_secrets` is failing in some scenarios
  tests/functional/adapter/test_python_model.py
Labels: cla:yes, Skip Changelog

#1099 [Backport] test_secret test update
  tests/functional/adapter/test_python_model.py
Labels: cla:yes, Skip Changelog
