Repository dbt-labs/dbt-snowflake, pull requests merged in 2024-03, with the labels that each got.

#920 allow for pre-release common/adapters
  setup.py
Labels: cla:yes, Skip Changelog

#921 Override test that was inadvertently added to the base test during the `dbt-tests-adapter` migration
  tests/functional/adapter/test_ephemeral.py
Labels: cla:yes, Skip Changelog

#926 use import instead of dbt --version for package check
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#932 Test ddtrace dependency range
  .changes/unreleased/Dependencies-20240319-102636.yaml
  dev-requirements.txt
Labels: cla:yes

#931 Add Snowflake internal build process workflow
  .changes/unreleased/Features-20240318-033136.yaml
  .github/workflows/release-internal.yml
Labels: cla:yes

#938 update cryptography to 42.0.4
  .changes/unreleased/Dependencies-20240320-111128.yaml
  dev-requirements.txt
Labels: cla:yes, backport 1.4.latest, backport 1.5.latest, backport 1.6.latest, backport 1.7.latest

#937 [Fix] Update dynamic table metadata queryies to take into account new object type.
  .changes/unreleased/Fixes-20240320-154054.yaml
  dbt/include/snowflake/macros/catalog.sql
  tests/functional/adapter/dynamic_table_tests/utils.py
Labels: cla:yes

#942 manual backport of pr 938
  .changes/unreleased/Fixes-20240320-154054.yaml
  dbt/include/snowflake/macros/catalog.sql
  tests/functional/adapter/dynamic_table_tests/utils.py
Labels: cla:yes

#940 [Backport ]uptick cryptography to 42.0.4 on 1.7.latest
  .changes/unreleased/Dependencies-20240320-124142.yaml
  dev-requirements.txt
Labels: cla:yes, backport 1.4.latest, backport 1.5.latest, backport 1.6.latest

#933 Acknowledge `send_anonymous_usage_stats` setting for python models
  .changes/unreleased/Fixes-20240318-203635.yaml
  dbt/adapters/snowflake/impl.py
  tests/functional/adapter/test_anonymous_usage_stats.py
Labels: cla:yes, backport 1.7.latest

#944 [Backport] uptick cryptography to 42.0.4 on 1.5.latest
  .changes/unreleased/Dependencies-20240320-111128.yaml
  dev-requirements.txt
Labels: cla:yes

#943 [Backport]uptick cryptography to 42.0.4
  .changes/unreleased/Dependencies-20240320-111128.yaml
  dev-requirements.txt
Labels: cla:yes

#950 Remove private_key_path from _conection_keys
  .changes/unreleased/Fixes-20240322-104553.yaml
  dbt/adapters/snowflake/connections.py
Labels: cla:yes, backport 1.6.latest, backport 1.7.latest

#945 Finish internal build workflow
  .github/workflows/release-internal.yml
  setup.py
Labels: cla:yes, Skip Changelog

#959 Pin `black>=24.3`
  .changes/unreleased/Security-20240327-190647.yaml
  dev-requirements.txt
Labels: cla:yes

#956 Test ddtrace dependency range 1.4.latest
  .changes/unreleased/Dependencies-20240319-102636.yaml
  dev-requirements.txt
Labels: cla:yes

#957 Test ddtrace dependency range (#932)
  .changes/unreleased/Dependencies-20240319-102636.yaml
  dev-requirements.txt
Labels: cla:yes

#958 soft pin pytest and use ddtrace 2.6.4
  dev-requirements.txt
Labels: cla:yes, Skip Changelog
