Repository dbt-labs/dbt-snowflake, pull requests merged in 2024-11, with the labels that each got.

#1230 move github runner from macos-12 to macos-14
  .github/scripts/integration-test-matrix.js
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#1233 remove SnowflakeAdapterResponse in favor of updated AdapterResponse in base
  .changes/unreleased/Under the Hood-20241106-113249.yaml
  dbt/adapters/snowflake/connections.py
  tests/unit/test_snowflake_adapter.py
Labels: cla:yes

#1192 [Microbatch] Optimizations: use view for temp relation + remove `using` clause during delete statement
  .changes/unreleased/Fixes-20241104-104610.yaml
  dbt/include/snowflake/macros/materializations/incremental.sql
  dbt/include/snowflake/macros/materializations/merge.sql
Labels: cla:yes

#1238 Update unit test mocks to handle the new `query_id` field
  tests/unit/test_snowflake_adapter.py
Labels: cla:yes, Skip Changelog

#1239 move github runner from macos-12 to macos-14 (#1230)
  .github/scripts/integration-test-matrix.js
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#1240 move github runner from macos-12 to macos-14 (#1230)
  .github/scripts/integration-test-matrix.js
  .github/workflows/main.yml
Labels: Skip Changelog

#1241 move github runner from macos-12 to macos-14 (#1230)
  .github/scripts/integration-test-matrix.js
  .github/workflows/main.yml
Labels: Skip Changelog

#1242 move github runner from macos-12 to macos-14 (#1230)
  .github/scripts/integration-test-matrix.js
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#1243 move github runner from macos-12 to macos-14 (#1230)
  .github/scripts/integration-test-matrix.js
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#1229 Normalize is_iceberg Field for Consistency in Snowflake with QUOTED_IDENTIFIERS_IGNORE_CASE
  .changes/unreleased/Fixes-20241104-172349.yaml
  dbt/adapters/snowflake/impl.py
  dbt/include/snowflake/macros/adapters.sql
  tests/functional/adapter/list_relations_tests/test_show_objects.py
Labels: cla:yes

#1235 Make `list_relations_without_caching` pagination configurable
  .changes/unreleased/Features-20241107-170307.yaml
  dbt/include/snowflake/macros/adapters.sql
  tests/functional/adapter/list_relations_tests/test_pagination.py
Labels: cla:yes, user docs

#1253 Adap 209/update iceberg docs note
  .changes/unreleased/Under the Hood-20241118-231637.yaml
  dbt/adapters/snowflake/impl.py
  dbt/include/snowflake/macros/relations/table/create.sql
Labels: cla:yes

#840 Handle non-English Snowflake error message for non-existing schemas
  .changes/unreleased/Fixes-20231129-124145.yaml
  dbt/adapters/snowflake/impl.py
Labels: cla:yes, ok to test, ready_for_review, community
