Repository dbt-labs/dbt-snowflake, pull requests merged in 2025-01, with the labels that each got.

#1289 Feature: Custom Iceberg `base_location_root`
  .changes/unreleased/Features-20250113-133414.yaml
  dbt/adapters/snowflake/impl.py
  dbt/adapters/snowflake/relation.py
  tests/functional/iceberg/models.py
  tests/functional/iceberg/test_table_basic.py
  tests/unit/test_iceberg_location.py
Labels: cla:yes

#1297 ADAP-1135: Update dbt-adapters ref to monorepo subdirectory
  dev-requirements.txt
Labels: cla:yes, Skip Changelog, backport 1.8.latest

#1304 [Backport 1.8.latest] Update dbt-adapters ref to monorepo subdirectory
  dev-requirements.txt
Labels: cla:yes, Skip Changelog
